BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "raspberrypi-minicarpet"
BBFILE_PATTERN_raspberrypi-minicarpet = "^${LAYERDIR}/"
BBFILE_PRIORITY_raspberrypi-minicarpet = "80"

LAYERVERSION_raspberrypi-minicarpet = "1"
LAYERSERIES_COMPAT_raspberrypi-minicarpet = "wrynose"

LAYERDEPENDS_raspberrypi-minicarpet = "raspberrypi swupdate"

# .is_layer_modified(...) evaluates to " -- modified" when the git workspace isnt clean
# we remove spaces, as this is used in a file name
LAYER_RASPBERRYPI_MINICARPET_MODIFIED = "${@oe.buildcfg.is_layer_modified(d.getVar('BBFILE_PATTERN_raspberrypi-minicarpet')[1:]).replace(' ', '')}"
LAYER_RASPBERRYPI_MINICARPET_REVISION = "${@oe.buildcfg.get_metadata_git_revision(d.getVar('BBFILE_PATTERN_raspberrypi-minicarpet')[1:])}"