BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "raspberrypi-logan"
BBFILE_PATTERN_raspberrypi-logan = "^${LAYERDIR}/"
BBFILE_PRIORITY_raspberrypi-logan = "80"

LAYERVERSION_raspberrypi-logan = "1"
LAYERSERIES_COMPAT_raspberrypi-logan = "wrynose"

LAYERDEPENDS_raspberrypi-logan = "raspberrypi swupdate"